# Copyright (c) 2023 Luiz Carlos Gili
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.



Import("env")

from os.path import abspath

files = env.FindSourceFiles(".")

if len(files) != 0:
    newenv = env.Clone()
    newenv.Append(CCFLAGS=["-w"]) # suppress all warnings
    library = newenv.StaticLibrary(target="mcal-ext", source=files)

    env.AppendUnique(LIBPATH=[
        abspath(str(library[0].get_dir())),
    ])

    env.AppendUnique(LIBS=[
        library,
    ])

    Return("library")
